# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e38bd0bd6ec78d7a71fc5f9e836e00e48d1579e8b988e70b6095640e9f2465c87af567d89686ab1578314ed649a7289ca74f5ffab8f05d32777d1841ed3ad4

test:
  secret_key_base: 689cfd9a02f0200427250ca3300a271afdb4ba4518042d0a6bbf59c9bbca5fddecf0e2dc7b23784b57702e88d195f5d417a3233a41fb1cc4f31e88b22f1594ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
